name: Build and publish sdist

on:
  push:
    branches:
      - main  # Change this to the main branch name, or use 'master' if that's the default branch.

jobs:
  build:
    name: Build sdist
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    
    - name: Build sdist
      run: |
        python -m pip install pybind11 numpy eigency
        python setup.py sdist --dist-dir wheelhouse
    
    - name: Run tests
      run: |
        python -m pip install pytest
        python -m pip install wheelhouse/*.tar.gz
        python -m pytest tests/*.py

    - name: Install Twine
      run: python -m pip install twine

    - name: Publish to PyPI
      if: github.event_name == 'push'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload wheelhouse/*